---
apiVersion: app.improvado.io/v1alpha1
kind: NginxIngress
metadata:
  name: test-ingress
spec:
  replicas: 1
  serviceAccount: nginx-ingress-operator
  nginxController:
    ingressClass: testicula
    runAsUser: 33
    image:
      repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
      tag: "0.24.1"
      pullPolicy: IfNotPresent
    config:
      use-proxy-protocol: "true"
      http2-max-field-size: 16k
  service:
    type: LoadBalancer
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
