---
apiVersion: app.improvado.io/v1alpha1
kind: NginxIngress
metadata:
  name: test-ingress
spec:
  replicas: 1
  serviceAccount: nginx-ingress-operator
  defaultBackend:
    name: pukipu
    port: 8080
    replicas: 1
    image:
      repository: k8s.gcr.io/defaultbackend-amd64
      tag: "1.5"
      pullPolicy: IfNotPresent
  nginxController:
    ingressClass: testicula
    runAsUser: 33
    publishService: true
    image:
      repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
      tag: "0.24.1"
      pullPolicy: IfNotPresent
    config:
      use-proxy-protocol: "true"
      http2-max-field-size: 16k
    configmap: test-ingress
  stats: 
    port: 9903
  metrics:
    port: 9902
    annotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "10254"
