// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngress":       schema_pkg_apis_app_v1alpha1_NginxIngress(ref),
		"github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngressSpec":   schema_pkg_apis_app_v1alpha1_NginxIngressSpec(ref),
		"github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngressStatus": schema_pkg_apis_app_v1alpha1_NginxIngressStatus(ref),
	}
}

func schema_pkg_apis_app_v1alpha1_NginxIngress(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NginxIngress is the Schema for the nginxingresses API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngressSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngressStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngressSpec", "github.com/tekliner/nginx-ingress-operator/pkg/apis/app/v1alpha1.NginxIngressStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_app_v1alpha1_NginxIngressSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NginxIngressSpec defines the desired state of NginxIngress",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_app_v1alpha1_NginxIngressStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NginxIngressStatus defines the observed state of NginxIngress",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
