apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress-operator
  template:
    metadata:
      labels:
        name: nginx-ingress-operator
    spec:
      containers:
        - name: nginx-ingress-operator
          image: operator
          imagePullPolicy: Always
          env:
          - name: WATCH_NAMESPACE
            value: ""
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: nginx-ingress-operator
          - name: SENTRY_DSN
            value: https://d459b0af58254d9194c16db3ff56c11e:b69a9ea1c0534e9f99e710f17d79f1e9@sentry.tools.improvado.io/42
      restartPolicy: Always
      serviceAccount: nginx-ingress-operator
      serviceAccountName: nginx-ingress-operator
