apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ingress-operator
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    - nodes
  verbs:
    - '*'
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
    - ingresses/status
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs:
    - '*'
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - create
- apiGroups:
    - app.improvado.io
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - '*'
